data:
    train: True
    window_length: 60

    BASE: "C:\\Users\\Handal\\github\\hiper-analysis-network\\timeseries\\data\\"
    end_name: "ambient_temperature_system_failure.csv"
    label: "labels\\combined_windows.json"
    data: "data\\realKnownCause\\"
    key: "realKnownCause/"

    visualize: True
    fill_timegap : True


args:
    train:
        workers: 1
        batch_size: 8
        epochs: 200
        lr: 0.0001
        cuda: True
        manualSeed: 2

    test:
        workers: 4
        batch_size: 10
